apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-222
spec:
  selector:
    matchLabels:
      app: app-222
  template:
    metadata:
      labels:
        app: app-222
    spec:
      containers:
      - image: nginx
        name: nginx
