apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-170
spec:
  selector:
    matchLabels:
      app: app-170
  template:
    metadata:
      labels:
        app: app-170
    spec:
      containers:
      - image: nginx
        name: nginx
