apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-279
spec:
  selector:
    matchLabels:
      app: app-279
  template:
    metadata:
      labels:
        app: app-279
    spec:
      containers:
      - image: nginx
        name: nginx
