apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-305
spec:
  selector:
    matchLabels:
      app: app-305
  template:
    metadata:
      labels:
        app: app-305
    spec:
      containers:
      - image: nginx
        name: nginx
