apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-169
spec:
  selector:
    matchLabels:
      app: app-169
  template:
    metadata:
      labels:
        app: app-169
    spec:
      containers:
      - image: nginx
        name: nginx
