apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-207
spec:
  selector:
    matchLabels:
      app: app-207
  template:
    metadata:
      labels:
        app: app-207
    spec:
      containers:
      - image: nginx
        name: nginx
