apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-51
spec:
  selector:
    matchLabels:
      app: app-51
  template:
    metadata:
      labels:
        app: app-51
    spec:
      containers:
      - image: nginx
        name: nginx
