apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-218
spec:
  selector:
    matchLabels:
      app: app-218
  template:
    metadata:
      labels:
        app: app-218
    spec:
      containers:
      - image: nginx
        name: nginx
