apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-231
spec:
  selector:
    matchLabels:
      app: app-231
  template:
    metadata:
      labels:
        app: app-231
    spec:
      containers:
      - image: nginx
        name: nginx
