apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-373
spec:
  selector:
    matchLabels:
      app: app-373
  template:
    metadata:
      labels:
        app: app-373
    spec:
      containers:
      - image: nginx
        name: nginx
