apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-184
spec:
  selector:
    matchLabels:
      app: app-184
  template:
    metadata:
      labels:
        app: app-184
    spec:
      containers:
      - image: nginx
        name: nginx
