apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-158
spec:
  selector:
    matchLabels:
      app: app-158
  template:
    metadata:
      labels:
        app: app-158
    spec:
      containers:
      - image: nginx
        name: nginx
