apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-167
spec:
  selector:
    matchLabels:
      app: app-167
  template:
    metadata:
      labels:
        app: app-167
    spec:
      containers:
      - image: nginx
        name: nginx
