apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-55
spec:
  selector:
    matchLabels:
      app: app-55
  template:
    metadata:
      labels:
        app: app-55
    spec:
      containers:
      - image: nginx
        name: nginx
