apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-320
spec:
  selector:
    matchLabels:
      app: app-320
  template:
    metadata:
      labels:
        app: app-320
    spec:
      containers:
      - image: nginx
        name: nginx
