apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-99
spec:
  selector:
    matchLabels:
      app: app-99
  template:
    metadata:
      labels:
        app: app-99
    spec:
      containers:
      - image: nginx
        name: nginx
