apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-253
spec:
  selector:
    matchLabels:
      app: app-253
  template:
    metadata:
      labels:
        app: app-253
    spec:
      containers:
      - image: nginx
        name: nginx
