apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-214
spec:
  selector:
    matchLabels:
      app: app-214
  template:
    metadata:
      labels:
        app: app-214
    spec:
      containers:
      - image: nginx
        name: nginx
