apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-377
spec:
  selector:
    matchLabels:
      app: app-377
  template:
    metadata:
      labels:
        app: app-377
    spec:
      containers:
      - image: nginx
        name: nginx
