apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-54
spec:
  selector:
    matchLabels:
      app: app-54
  template:
    metadata:
      labels:
        app: app-54
    spec:
      containers:
      - image: nginx
        name: nginx
