apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-10
spec:
  selector:
    matchLabels:
      app: app-10
  template:
    metadata:
      labels:
        app: app-10
    spec:
      containers:
      - image: nginx
        name: nginx
