apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3
spec:
  selector:
    matchLabels:
      app: app-3
  template:
    metadata:
      labels:
        app: app-3
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-3-43
spec:
  ports:
  - port: 80
  selector:
    app: app-43
---
apiVersion: v1
kind: Service
metadata:
  name: svc-3-47
spec:
  ports:
  - port: 80
  selector:
    app: app-47
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-4
spec:
  selector:
    matchLabels:
      app: app-4
  template:
    metadata:
      labels:
        app: app-4
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-5
spec:
  selector:
    matchLabels:
      app: app-5
  template:
    metadata:
      labels:
        app: app-5
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-6
spec:
  selector:
    matchLabels:
      app: app-6
  template:
    metadata:
      labels:
        app: app-6
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-6-36
spec:
  ports:
  - port: 80
  selector:
    app: app-36
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-7
spec:
  selector:
    matchLabels:
      app: app-7
  template:
    metadata:
      labels:
        app: app-7
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-7-6
spec:
  ports:
  - port: 80
  selector:
    app: app-6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-8
spec:
  selector:
    matchLabels:
      app: app-8
  template:
    metadata:
      labels:
        app: app-8
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-8-25
spec:
  ports:
  - port: 80
  selector:
    app: app-25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-9
spec:
  selector:
    matchLabels:
      app: app-9
  template:
    metadata:
      labels:
        app: app-9
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-10
spec:
  selector:
    matchLabels:
      app: app-10
  template:
    metadata:
      labels:
        app: app-10
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-10-14
spec:
  ports:
  - port: 80
  selector:
    app: app-14
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-11
spec:
  selector:
    matchLabels:
      app: app-11
  template:
    metadata:
      labels:
        app: app-11
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-12
spec:
  selector:
    matchLabels:
      app: app-12
  template:
    metadata:
      labels:
        app: app-12
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-13
spec:
  selector:
    matchLabels:
      app: app-13
  template:
    metadata:
      labels:
        app: app-13
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-14
spec:
  selector:
    matchLabels:
      app: app-14
  template:
    metadata:
      labels:
        app: app-14
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-15
spec:
  selector:
    matchLabels:
      app: app-15
  template:
    metadata:
      labels:
        app: app-15
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-15-50
spec:
  ports:
  - port: 80
  selector:
    app: app-50
---
apiVersion: v1
kind: Service
metadata:
  name: svc-15-7
spec:
  ports:
  - port: 80
  selector:
    app: app-7
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-16
spec:
  selector:
    matchLabels:
      app: app-16
  template:
    metadata:
      labels:
        app: app-16
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-17
spec:
  selector:
    matchLabels:
      app: app-17
  template:
    metadata:
      labels:
        app: app-17
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-18
spec:
  selector:
    matchLabels:
      app: app-18
  template:
    metadata:
      labels:
        app: app-18
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-19
spec:
  selector:
    matchLabels:
      app: app-19
  template:
    metadata:
      labels:
        app: app-19
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-19-6
spec:
  ports:
  - port: 80
  selector:
    app: app-6
---
apiVersion: v1
kind: Service
metadata:
  name: svc-19-41
spec:
  ports:
  - port: 80
  selector:
    app: app-41
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-20
spec:
  selector:
    matchLabels:
      app: app-20
  template:
    metadata:
      labels:
        app: app-20
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-21
spec:
  selector:
    matchLabels:
      app: app-21
  template:
    metadata:
      labels:
        app: app-21
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-22
spec:
  selector:
    matchLabels:
      app: app-22
  template:
    metadata:
      labels:
        app: app-22
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-22-18
spec:
  ports:
  - port: 80
  selector:
    app: app-18
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-23
spec:
  selector:
    matchLabels:
      app: app-23
  template:
    metadata:
      labels:
        app: app-23
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-24
spec:
  selector:
    matchLabels:
      app: app-24
  template:
    metadata:
      labels:
        app: app-24
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-25
spec:
  selector:
    matchLabels:
      app: app-25
  template:
    metadata:
      labels:
        app: app-25
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-25-7
spec:
  ports:
  - port: 80
  selector:
    app: app-7
---
apiVersion: v1
kind: Service
metadata:
  name: svc-25-18
spec:
  ports:
  - port: 80
  selector:
    app: app-18
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-26
spec:
  selector:
    matchLabels:
      app: app-26
  template:
    metadata:
      labels:
        app: app-26
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-27
spec:
  selector:
    matchLabels:
      app: app-27
  template:
    metadata:
      labels:
        app: app-27
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-28
spec:
  selector:
    matchLabels:
      app: app-28
  template:
    metadata:
      labels:
        app: app-28
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-29
spec:
  selector:
    matchLabels:
      app: app-29
  template:
    metadata:
      labels:
        app: app-29
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-30
spec:
  selector:
    matchLabels:
      app: app-30
  template:
    metadata:
      labels:
        app: app-30
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-30-35
spec:
  ports:
  - port: 80
  selector:
    app: app-35
---
apiVersion: v1
kind: Service
metadata:
  name: svc-30-41
spec:
  ports:
  - port: 80
  selector:
    app: app-41
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-31
spec:
  selector:
    matchLabels:
      app: app-31
  template:
    metadata:
      labels:
        app: app-31
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-32
spec:
  selector:
    matchLabels:
      app: app-32
  template:
    metadata:
      labels:
        app: app-32
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-33
spec:
  selector:
    matchLabels:
      app: app-33
  template:
    metadata:
      labels:
        app: app-33
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-34
spec:
  selector:
    matchLabels:
      app: app-34
  template:
    metadata:
      labels:
        app: app-34
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-35
spec:
  selector:
    matchLabels:
      app: app-35
  template:
    metadata:
      labels:
        app: app-35
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-36
spec:
  selector:
    matchLabels:
      app: app-36
  template:
    metadata:
      labels:
        app: app-36
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-37
spec:
  selector:
    matchLabels:
      app: app-37
  template:
    metadata:
      labels:
        app: app-37
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-37-13
spec:
  ports:
  - port: 80
  selector:
    app: app-13
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-38
spec:
  selector:
    matchLabels:
      app: app-38
  template:
    metadata:
      labels:
        app: app-38
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-39
spec:
  selector:
    matchLabels:
      app: app-39
  template:
    metadata:
      labels:
        app: app-39
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-39-17
spec:
  ports:
  - port: 80
  selector:
    app: app-17
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-40
spec:
  selector:
    matchLabels:
      app: app-40
  template:
    metadata:
      labels:
        app: app-40
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-40-24
spec:
  ports:
  - port: 80
  selector:
    app: app-24
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-41
spec:
  selector:
    matchLabels:
      app: app-41
  template:
    metadata:
      labels:
        app: app-41
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-42
spec:
  selector:
    matchLabels:
      app: app-42
  template:
    metadata:
      labels:
        app: app-42
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-43
spec:
  selector:
    matchLabels:
      app: app-43
  template:
    metadata:
      labels:
        app: app-43
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-44
spec:
  selector:
    matchLabels:
      app: app-44
  template:
    metadata:
      labels:
        app: app-44
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-45
spec:
  selector:
    matchLabels:
      app: app-45
  template:
    metadata:
      labels:
        app: app-45
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-46
spec:
  selector:
    matchLabels:
      app: app-46
  template:
    metadata:
      labels:
        app: app-46
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-46-5
spec:
  ports:
  - port: 80
  selector:
    app: app-5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-47
spec:
  selector:
    matchLabels:
      app: app-47
  template:
    metadata:
      labels:
        app: app-47
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-48
spec:
  selector:
    matchLabels:
      app: app-48
  template:
    metadata:
      labels:
        app: app-48
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-49
spec:
  selector:
    matchLabels:
      app: app-49
  template:
    metadata:
      labels:
        app: app-49
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: svc-49-22
spec:
  ports:
  - port: 80
  selector:
    app: app-22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-50
spec:
  selector:
    matchLabels:
      app: app-50
  template:
    metadata:
      labels:
        app: app-50
    spec:
      containers:
      - image: nginx
        name: nginx
